#单数据源
spring:
  datasource:
      name: test
      url: jdbc:mysql://39.108:3306/mydb01?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
      username: root
      password: Java2018
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

#mybatis配置
mybatis:
  config-location: classpath:mapper/*Mapper.xml