#多数据源
spring:
  datasource:
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://rm-.mysql.rds.aliyuncs.com:3306/mydb02?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Java2018
    driverClassName: com.mysql.jdbc.Driver
## cluster 数据源配置
cluster:
  datasource:
    url: jdbc:mysql://rm-.mysql.rds.aliyuncs.com:3306/mydb01?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Java2018
    driverClassName: com.mysql.jdbc.Driver

